### PR TITLE
Upgrade Small Tasks

### PR DESCRIPTION
**Pull request by daredoes**
Adds a small task that claims the daily reward automatically so the bot does not stop when the server begins a new day

### CODE REVIEW

**Comment by 9-9-9-9** [comment]
Hi @daredoes
Since I don't play this game anymore and won't test if your implementation works or not, so feel free to merge everything yourself.
On behalf of community, thanks for taking over this project

**Comment by daredoes** [comment]
Thanks for all your great work on this tool!

**Comment by 9-9-9-9** [comment]
@daredoes bump 3.7.0 please, I'll release after this merged

**Comment by daredoes** [comment]
tested locally, working, merge, will do a new release soon

**Pull request merged**
